RUBY/rails/demo_app/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'user#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/ciphers', to: 'ciphers#create'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RUBY/rails/demo_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RUBY/rails/demo_app/app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  # save email to database as downcase form
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\d+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum:100 },
                format: { with: VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false}
    
  validates :password, presence: true, length: {minimum:6}, allow_blank: true
  has_secure_password

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  #add token
  def remember 
    #get random token
    self.remember_token = User.new_token
    # save the encrypted token to database
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  #remove token
  def forget
    update_attribute(:remember_digest, nil)
  end

  #check given token is matches encrypted version in database
  def authenticated?(remember_token)
    # check if remeber_digest of current user is nil
    return false if remember_digest.nil?
    # compare old token and given token
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

end

RUBY/rails/demo_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
end

RUBY/rails/demo_app/app/controllers/ciphers_controller.rb
class CiphersController < ApplicationController
  def create
    input_string = params[:string]
    position = params[:position].to_i
    result = ceaser_cipher(input_string, position)
    p result
    respond_to do |format|
      format.json { render json: result}
    end
  end
end

RUBY/rails/demo_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # get page login
  def new
    redirect_to root_url if logged_in?
  end

  #login with Post request
  def create
    user =  User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # login successfully
      # save user's id to session
      log_in user

      #check whether 'remember me' checkbox is checked or not
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)

      redirect_back_or user_url(user)
    else
      flash.now[:danger] = "Invalid information"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    flash[:success] = "Log out successfully"
    redirect_to root_url
  end
end

RUBY/rails/demo_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    flash[:danger] = "You must login"
    redirect_to login_url unless logged_in?
  end

  def help
  end

  def about
  end

  def contact
  end
end

RUBY/rails/demo_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  #only logged-in user has ability to perform these actions
  before_action :logged_user_in, only: [:index, :edit, :update, :show, :destroy]
  # current user wasn't allowed to access other user's information and he/she only view and update his/her information
  before_action :not_same_user,  only: [:show, :edit, :update]
  # only admin can destroy normal user
  before_action :admin_user,     only: :destroy

  def index
    #pagination
    @users = User.paginate(page: params[:page], per_page: 7)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
     @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save 
      #create user successfully
      flash[:success] = "Login to the page"
      redirect_to user_url(@user)
    else
      render 'new'
    end
  end
    
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # update successfully
      flash[:success] = "Profile updated!"
      redirect_to user_url(@user)
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id]).delete  
    flash[:success] = "Delete #{ @user.email } successfully!"
    redirect_to users_url
  end

  private
    
  # use strong parameter to get valid information to create or update user
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
  
  # the current user cannot access to another user's information 
  def not_same_user
    @user = User.find(params[:id])
     if (!current_user?(@user) && !current_user.admin?)
       flash[:danger] = "You can not access to #{ @user.email }"
       redirect_to root_url
     end
  end

  def logged_user_in
    # if user haven't logged in then forcing user must log in
    unless logged_in?
      # save current url to forward if user log in later
      store_location
      flash[:danger] = "You have to sign your account to the page"
      redirect_to login_url
    end
  end

  def admin_user
    redirect_to root_url unless current_user.admin?
  end

end

RUBY/rails/demo_app/app/helpers/application_helper.rb
module ApplicationHelper
end

RUBY/rails/demo_app/app/helpers/ciphers_helper.rb
module CiphersHelper
end

RUBY/rails/demo_app/app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  # set current user
  def current_user
    # check if user is existed in session
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    # else if cookie has user
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      #check if user is valid and remember token in cookie is match the one in database
      if user && user.authenticated?(cookies[:remember_token])
        p user && user.authenticated?(cookies[:remember_token])
        #save user's id to current session and set user to current user
        log_in user 
        @current_user = user
      end
    end
  end

  #check user is current user?
  def current_user?(user)
    user == current_user
  end

  # if current user is existed so he logged in
  def logged_in?
    !current_user.nil?
  end

  def log_out
    #delete session and cookie
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def remember(user)
    #add encrypted remember token to db
    user.remember
    # add remember token to cookie
    cookies.permanent[:remember_token] = user.remember_token
    # add encrypted user's id to cookie
    cookies.permanent.signed[:user_id] = user.id
  end

  def forget(user)
    #set encrypted remember token in databse is nil
    user.forget
    #delete information in cookie
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  #redirect to stored location(or to the default)
  def redirect_back_or(default)
    redirect_to (session[:forwarding_url] || default)
    # delete after forwarding
    session.delete(:forwarding_url)
  end
      
  #store the url trying to be accessing
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

RUBY/rails/demo_app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

RUBY/rails/demo_app/app/helpers/users_helper.rb
module UsersHelper
end

RUBY/rails/demo_app/app/views/ciphers/create.html.erb
<h1>Ciphers#create</h1>
<p>Find me in app/views/ciphers/create.html.erb</p>

RUBY/rails/demo_app/app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small> Ceaser Cipher &copy; 2018</small>
        <ul>
            <li>
                <%= link_to "About", about_path %>
            </li>
            <li>
                <%= link_to "Contact", contact_path %>
            </li>
        </ul>
    </footer>
</div>

RUBY/rails/demo_app/app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <div class="navbar-brand">
                <%= link_to  "Ceaser Ciphered", root_url %>
            </div>
        </div>

        <ul class="nav navbar-nav">
            <li>
                <%= link_to  "Home", root_url %>
            </li>
            <li>
                <%= link_to  "Help", help_url %>
            </li>
            <li>
                <%= link_to  "About", about_url %>
            </li>
            <li>
                <%= link_to  "Contact", contact_url %>
            </li>
        </ul>
       
        <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
                <% if current_user.admin? %>
                <li><%= link_to  "Users", users_path %></li>
                <% end %>
                
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Account
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><%= link_to  "Profile", user_url(current_user) %></li>
                        <li><%= link_to  "Setting", edit_user_url(current_user) %></li>
                        <li><%= link_to  "Log out", logout_url, method: "delete" %></li>
                    </ul>
                </li>
            <% else %>
                <li>
                    <%= link_to  "Log in", login_url %>
                </li>
            <% end %>
        </ul>
    </div>
</header>

RUBY/rails/demo_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render  "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

RUBY/rails/demo_app/app/views/shared/_error_message.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "errors") %>    
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
      <% end %> 
    </ul>
  </div>
<% end %>

RUBY/rails/demo_app/app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

RUBY/rails/demo_app/app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

RUBY/rails/demo_app/app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

RUBY/rails/demo_app/app/views/static_pages/home.html.erb
<% provide(:title, 'Home')%>
<div class="row home">
    <div class="col-md-10 col-md-offset-1">
        <h1>Ceaser Cipher</h1>
        <blockquote>
            Caesar cipher, also known as Caesar's cipher, the shift cipher, Caesar's code or Caesar shift, is one of the simplest and most widely known encryption techniques
            <div class="well">
                <p>Example: </p>
                <p>Input: a / position: 1</p>
                <p>Output: b</p>
            </div>
        </blockquote>
        <p class="errorMessage"></p>
        <div class="col-md-6">
            <div class="panel panel-info">
                <div class="panel-heading">Input</div>
                <div class="panel-body">
                    <textarea name="" id="inputCipher" cols="40" rows="5"></textarea> <span>/</span> 
                    <input type="text" id="numberPosition">
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="panel panel-success">
                <div class="panel-heading">Output</div>
                <div class="panel-body">
                    <textarea name="" id="outputCipher"  cols="40" rows="5" disabled></textarea>
                </div>
            </div>
        </div>

        <button id="sendInput" class="btn btn primary"> Send </button>
    </div>
</div>

<script type="text/javascript">
    <%= render  "ajax_call.js" %>
</script>

RUBY/rails/demo_app/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render  "shared/error_message" %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: 'btn btn-primary signup-button' %>
<% end %>

RUBY/rails/demo_app/app/views/users/edit.html.erb
<% provide(:title, 'Update')%>
<% provide(:button_text, "Save changes")%>
<div class="row form">
    <div class="col-md-6 col-md-offset-3">
        <h1>Update information</h1>
        <%= render "form" %>
    </div>
</div>

<script type="text/javascript">
    <%= render "validation.js" %>
</script>

RUBY/rails/demo_app/app/views/users/index.html.erb
<% provide(:title, "All users")%>
<div class="row">
        <div class="col-md-10 col-md-offset-1">
            <h1>All Users</h1>
            <%= will_paginate %>
            <table class="table table-bordered table-hover">
                <thead>
                    <th>Email</th>
                    <th>Action</th>
                </thead>
                <tbody>
                    <% @users.each do |user| %>
                    <tr>
                        <td class="col-md-9">
                            <%= user.email %>
                        </td>
                          <td class="col-md-3">
                            <%= link_to  "Detail", user_url(user), class: "btn btn-info" %>
                            <% if current_user.admin? && !current_user?(user) %>
                              <%= link_to  "Edit", edit_user_url(user), class: "btn btn-primary" %>
                              <%= link_to  "Delete", user, method: :delete,
                                                    data: { confirm: "Are you sure delete #{user.email}"},
                                                    class: "btn btn-danger" %>
                            <% end %>
                          </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
            <%= will_paginate %>
        </div>
    </div>
    
    

RUBY/rails/demo_app/app/views/users/new.html.erb
<% provide(:title, "Sign up")%>
<% provide(:button_text, "Create")%>
<div class="row form">
    <div class="col-md-6 col-md-offset-3">
        <h1>Create a new account</h1>
        <%= render "form" %>
    </div>
</div>

<script type="text/javascript">
    <%= render "validation.js" %>
</script>

RUBY/rails/demo_app/app/views/users/show.html.erb
<% provide(:title, "Profile")%>

<div class="row">
    <div class="col-md-6 img">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvzOpl3-kqfNbPcA_u_qEZcSuvu5Je4Ce_FkTMMjxhB-J1wWin-Q"
            alt="" class="img-rounded">
    </div>
    <div class="col-md-6 details">
        <blockquote>
            <h5>Information</h5>
            <small><cite title="Source Title">Somewhere on earth <i class="icon-map-marker"></i></cite></small>
        </blockquote>
        <p>
            Email: <%= @user.email %> <br>
            <% if @user.admin %>
            Role: Admin
            <% else%>
            Role: User 
            <% end %>
            <br>
            Created at: <%= @user.created_at %>
        </p>
    </div>
</div>